version: 2

updates:

  - package-ecosystem: npm
    directory: /
    target-branch: deps/npm
    schedule:
      interval: daily
      time: "10:05" 
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /
    target-branch: master
    schedule:
      interval: daily
      time: "10:05" 
    open-pull-requests-limit: 10
